packages:
  - apps/*
  - packages/*

allowBuilds:
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  bufferutil: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

onlyBuiltDependencies:
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - bufferutil
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
