import { db } from "./index";
import { questions } from "./schema";

const questionData = [
  // --- Original Prompts ---
  "The bizarre reality TV show crossover",
  "The little known mythical creature",
  "The work of the world's worst tattoo artist",
  "The surprising winner of a child's beauty pageant",
  "The unexpected product placement in a classic movie",
  "The surprise guest at a presidential inauguration",
  "The unexpected product endorsement by your mom",
  "The absurd remake of a classic movie with a twist",
  "The futuristic invention that revolutionizes breakfast",
  "The surprising addition to the royal family",
  "The controversial redesign of a beloved cartoon character",
  "The unexpected collaboration between Santa Claus and the Easter Bunny",
  "The YouTube prank that went way over the line",
  "The collector and the odd type of item they collect",
  "Who your grandma is cheating on your grandpa with",
  "The unlikely mascot for a sports team",
  "You in an alternate diemension",
  "The dystopian version of a popular TV show",
  "Not the expected location to have an extravagant resort",
  "The celebrity chef's secret ingredient that no one saw coming",
  "The unexpected pop-up shop in Hogwarts",
  "The surprising superhero crossover everyone has been waiting for",
  "When Disney characters get stuck in The Twilight Zone",
  "The coolest way to die",
  "The awkward moment caught on a celebrity's Instagram",
  "The uninvited wedding guest",
  "The bizarre food combination that became a viral sensation",
  "The bizarre invention at a technology fair",
  "The bizarre tourist attraction that becomes an internet sensation",
  "The new challenger in Super Smash Bros",
  "The bizarre item found inside a time capsule",
  "The unexpected result of a science experiment",
  "The road trip destination you don't want to stay very long at",
  "The unexpected mascot for a famous fast-food chain",
  "The hit new musical about the Department of Motor Vehicles (DMV)",
  "The Starbucks drink that becomes more popular than the Pumpkin Spice Latte",
  "The secret ingredient in the Big Mac",
  "The strange event that happens once every 100 years",
  "The unlikely celebrity endorsement",
  "And the Oscar goes to:",
  "The secret ingredient in Elon Musk's rocket fuel",
  "The latest fashion trend in the zombie apocalypse",
  "The celebrity hiding in your closet",
  "The unconventional superhero power",
  "The mysterious ghost haunting a famous landmark",
  "The lost treasure hidden in a famous landmark",
  "The celebrity who secretly runs a fast food chain",
  "The local news segment no one asked for",
  "Not the normal kind of rainy weather",
  "The cosplay costume that takes some guts to wear",
  "First thing to do when going back in time",
  "The cause of the world's next famine",
  "The surprising invention that revolutionizes household chores",
  "The famous action movie scene reimagined with puppies",
  "The secret ingredient discovered in Coca-Cola",
  "The marriage proposal method with a 0% success rate",
  "A disastrous cooking show episode",
  "The bizarre fashion trend taking over the runway",
  "The offbeat high school club with only one member",
  "The alien invasion during a music concert",
  "The new addition to Mount Rushmore",
  "Sports in the year 3000",
  "The world's most outrageous fashion trend",
  "The superhero with the strangest superpower",
  "The celebrity chef's secret ingredient",
  "The unexpected collaboration between two iconic musicians",
  "The bizarre invention from Elon Musk",
  "The surprising comeback of a long-forgotten fashion trend",
  "A welcome surprise when entering your apartment",
  "The bizarre superhero power that nobody wants",
  "The celebrity chef's disastrous cooking show",
  "The unexpected outcome of a blind date with a famous historical figure",
  "The last thing you want to happen while sitting on the toilet",
  "The inanimate object no one wants to come to life",
  "The secret ingredient in Coca-Cola",
  "The oft-forgotten fruit from the Amazon Rainforest",
  "The unexpected outcome of a jellybean taste test",
  "The world's worst superhero sidekick",
  "The unexpected celebrity guest at a high school reunion no one wanted to see again",
  "The hidden room in the White House",
  "Throw out the air fryer, this is the only kitchen appliance everyone needs",
  "What bigfoot actually is",
  "The wacky invention for lazy people",
  "The interesting conspiracy theory behind the Easter Island heads",
  "The cartoon character who would make the best candidate for president of the United States",
  "The school bus driver you don't trust to drive your kids",
  "The peculiar mascot for a fast-food chain",
  "The easiest way to make a profit",
  "The unconventional method for catching a Pokemon",
  "The hilarious mix-up at a Harry Potter convention",
  "The surprise winner of America's Got Talent",
  "The unexpected collaboration between your favorite musicians",
  "Mona Lisa in today's day and age",
  "The alien invasion during a rock concert",
  "The unconventional superhero saving the world",
  "The TED Talk that would instantly sell out",
  "When the celebrity chef's latest culinary creation came alive",
  "The secret life of Batman",
  "The celebrity pet fashion show",
  "The unconventional way to propose marriage",
  "The mysterious creature lurking in the sewers",
  "The alternate ending of Game of Thrones",
  "The newly discovered animal in Australia",
  "What makes the world's spiciest hot sauce so spicy",
  "A magic trick that did not go as planned",
  "The new Olympic sport",
  "The surprising celebrity couple nobody saw coming",
  "The celebrity-inspired fashion trend that everyone regrets trying",
  "The reality TV show where historical figures compete for the ultimate prize",
  "The commercial you see on TV at 2am while sitting in the lobby of the hospital",
  "The unexpected twist in a famous movie ending",
  "The secret ingredient in Colonel Sanders' famous fried chicken recipe",
  "The bizarre invention from an alternate universe",
  "The bizarre product on a late-night infomercial",
  "The strange thing found in a fast food burger",
  "What you don't expect to see flying in a tornado",
  "The mischievous surprise in a McDonald's Happy Meal",
  "The creature hidden in IKEA",
  "The hidden message in a famous painting",
  "Worst place to take a poop",
  "The scandalous secret of the rich and famous",
  "Latest Netflix dating show everyone is raving about",
  "What the newest invite-only restaurant in town serves",
  "The unexpected outcome of a famous historical event",
  "The bizarre results of a mad scientist's experiment",
  "The unexpected collaboration between Santa Claus and the Tooth Fairy",
  "The unexpected spokes-animal for a popular cereal brand",
  "The unexpected side effect of eating too much ice cream",
  "The forbidden love affair between two iconic fictional characters",
  "The embarrassing wardrobe malfunction at a prestigious awards show",
  "What is drawn on the whiteboard after the teacher leaves the classroom",
  "The surprise halftime show at the Super Bowl",
  "Two brands no one anticipated would collaborate",
  "The bizarre celebrity fashion trend",
  "The unexpected twist in a classic fairy tale",
  "The unexpected collaboration between two famous musicians",
  "The worst superhero sidekick",
  "Something that should not have a sequin texture",
  "What a factory making the latest iPhone probably looks like",
  "A movie genre mashup",
  "The questionable product advertised during the Super Bowl",
  "The alternative ending to the Harry Potter series",
  "The unusual pet that became an internet sensation",
  "The secret ingredient in Coca-Cola's recipe",
  "The secret ingredient that makes Coca-Cola so addictive",
  "An awkward yet strangely beautiful family photo",
  "The substance preventing you from sitting on the last remaining seat of the bus",
  "The unconventional superhero origin story",
  "The prank gone wrong at the White House",
  "The mascot for a failed fast food chain",
  "The bizarre new dance move that goes viral",
  "The unexpected winner of the Nobel Peace Prize",
  "The real reason the pyramids were built",
  "A cancelled children's toy",
  "The unexpected twist in a summer blockbuster",
  "The next evolution of Quidditch",
  "The secret room in the White House",
  "Your niece's unorthodox stuffed animal",
  "Where dad is now after leaving to go buy milk from the gas station and never coming back",
  "Undeniably the world's cutest animal",
  "The celebrity makeover gone horribly wrong",
  "The unexpected shape of the Loch Ness monster",
  "The board game that could also be considered a war crime",
  "Oops, we now have unlimited of this because of a failed science experiment",
];

async function seed() {
  console.log("Seeding questions...");

  const insertedQuestions = await db
    .insert(questions)
    .values(questionData.map((text) => ({ text })))
    .onConflictDoNothing()
    .returning();

  console.log(`Seeded ${insertedQuestions.length} questions`);
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seeding failed:", error);
  process.exit(1);
});
